types.tower=[
    {
        name:'',size:0,
        levels:[
            {effect:[],reload:0,range:0,hidden:false,lcost:0},
        ],
    },{
        name:'Scout',size:15,
        levels:[
            {effect:[1,'Physical'],reload:60,range:100,hidden:false,lcost:250},
        ],
    }
]