types={
    map:[
        {
            name:'Polluted Wasteland',
            path:[
                'DDDDDDDDRRRRRRRRRRUUUULLLLDDDDDDDDRRRRUUUULLLLLLLLUUUURRRRDDDDDDDDLLLLUUUURRRRRRRRRRDDDDDDDD',
            ],
        },
    ],
}
stage={scale:0,scene:'level'}
game={speed:0,speeds:[1,2,4,6],timer:0,mode:0,map:0,path:[],towers:[1,1,1,1,1,1,1,1],sortedEnemies:[],money:1000,lives:100}
entities={enemies:[],towers:[],spawner:0,ui:0}
run={fore:[entities.towers,entities.enemies],info:[entities.towers,entities.enemies]}
graphics={main:0,backgrounds:[]}
transition={trigger:false,anim:0,scene:stage.scene}
inputs={mouse:{x:0,y:0},rel:{x:0,y:0}}
a=0;b=0;c=0;d=0;e=0;f=0;g=0;h=0;i=0;j=0;k=0;l=0;m=0;n=0;o=0;p=0
la=0;lb=0;lc=0;ld=0;le=0;lf=0;lg=0;lh=0;li=0;lj=0;lk=0;ll=0;lm=0;ln=0;lo=0;lp=0